# Generated by Django 5.2.10 on 2026-06-26 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('purchase_item_name', models.CharField(max_length=100)),
                ('generic_item_name', models.CharField(max_length=100)),
                ('storage_location', models.CharField(choices=[('dry_pantry', 'Dry Pantry'), ('walk_in', 'Walk-in Cooler'), ('reach_in', 'Reach-in Fridge'), ('freezer', 'Freezer')], max_length=50)),
                ('kitchen_location', models.CharField(choices=[('london', 'Cloud Kitchen London'), ('new_york', 'Cloud Kitchen New York'), ('tokyo', 'Cloud Kitchen Tokyo')], default='london', max_length=50)),
                ('par_level', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('qty_on_hand', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orchestrator.inventorycategory')),
                ('purchase_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items', to='orchestrator.inventoryunit')),
                ('recipe_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='orchestrator.inventoryunit')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(default='Operations Manager', max_length=100)),
                ('profile_pic_url', models.CharField(default='https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=80&fit=crop&q=80', max_length=500)),
                ('currency', models.CharField(choices=[('AED', 'AED (dirham)'), ('USD', '$ (USD)'), ('GBP', '£ (GBP)'), ('EUR', '€ (EUR)')], default='AED', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
