# Generated by Django 5.2.10 on 2026-06-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0002_vendor_inventoryitem_invoice_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='invoice_image',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
