# Generated by Django 5.2.10 on 2026-06-27 13:33

import django.db.models.deletion
from django.db import migrations, models


def seed_and_map_locations(apps, schema_editor):
    StorageLocation = apps.get_model('orchestrator', 'StorageLocation')
    KitchenLocation = apps.get_model('orchestrator', 'KitchenLocation')
    InventoryItem = apps.get_model('orchestrator', 'InventoryItem')

    s1, _ = StorageLocation.objects.get_or_create(name='Dry Pantry')
    s2, _ = StorageLocation.objects.get_or_create(name='Walk-in Cooler')
    s3, _ = StorageLocation.objects.get_or_create(name='Reach-in Fridge')
    s4, _ = StorageLocation.objects.get_or_create(name='Freezer')

    k1, _ = KitchenLocation.objects.get_or_create(name='Hessa Street')
    k2, _ = KitchenLocation.objects.get_or_create(name='JBR')
    k3, _ = KitchenLocation.objects.get_or_create(name='Meydan')

    # Update choices to string IDs before column alteration
    InventoryItem.objects.filter(storage_location='dry_pantry').update(storage_location=str(s1.id))
    InventoryItem.objects.filter(storage_location='walk_in').update(storage_location=str(s2.id))
    InventoryItem.objects.filter(storage_location='reach_in').update(storage_location=str(s3.id))
    InventoryItem.objects.filter(storage_location='freezer').update(storage_location=str(s4.id))

    InventoryItem.objects.filter(kitchen_location='london').update(kitchen_location=str(k1.id))
    InventoryItem.objects.filter(kitchen_location='new_york').update(kitchen_location=str(k2.id))
    InventoryItem.objects.filter(kitchen_location='tokyo').update(kitchen_location=str(k3.id))

    # Catch-all for any other values or already-migrated values
    for item in InventoryItem.objects.all():
        if not item.storage_location or not item.storage_location.isdigit():
            item.storage_location = str(s1.id)
            item.save()
        if not item.kitchen_location or not item.kitchen_location.isdigit():
            item.kitchen_location = str(k1.id)
            item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0003_inventoryitem_invoice_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RunPython(seed_and_map_locations),
        migrations.AlterField(
            model_name='inventoryitem',
            name='kitchen_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orchestrator.kitchenlocation'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='storage_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orchestrator.storagelocation'),
        ),
    ]
