# Generated by Django 5.2.10 on 2026-06-27 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0004_kitchenlocation_storagelocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='kitchen_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orchestrator.kitchenlocation'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='storage_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orchestrator.storagelocation'),
        ),
    ]
