# Generated by Django 5.2.10 on 2026-06-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0005_alter_inventoryitem_kitchen_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='recipe_unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
