# Generated by Django 5.2.10 on 2026-07-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0006_inventoryitem_recipe_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='audit',
            field=models.CharField(choices=[('Verified', 'Verified'), ('To be verified', 'To be verified')], default='Verified', max_length=20),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='audit_notes',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
