# Generated by Django 5.2.10 on 2026-07-04 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0007_inventoryitem_audit_inventoryitem_audit_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='audit',
            field=models.CharField(choices=[('Issue', 'Issue'), ('Verified', 'Verified')], default='Verified', max_length=20),
        ),
    ]
