# Generated by Django 5.2.10 on 2026-07-06 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0008_alter_inventoryitem_audit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=200)),
                ('client_name', models.CharField(blank=True, default='', max_length=200)),
                ('cuisine', models.CharField(blank=True, default='', max_length=100)),
                ('servings', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('actual_selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('portion_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('portion_food_cost_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('subcategory', models.CharField(blank=True, default='', max_length=100)),
                ('price_without_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vat_pct', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('comment', models.TextField(blank=True, default='')),
                ('allergen', models.CharField(blank=True, default='', max_length=500)),
                ('preparation_steps', models.TextField(blank=True, default='')),
                ('packaging_type', models.CharField(blank=True, default='', max_length=100)),
                ('packaging_cost_with_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('approved_by_chef', models.CharField(blank=True, default='', max_length=200)),
                ('food_image_url', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='audit',
            field=models.CharField(choices=[('Issue', 'Issue'), ('Verified', 'Verified')], default='Issue', max_length=20),
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_name', models.CharField(blank=True, default='', max_length=200)),
                ('purchase_name', models.CharField(blank=True, default='', max_length=200)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('qty', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('order', models.IntegerField(default=0)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='orchestrator.recipe')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
