# Generated by Django 5.2.10 on 2026-07-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0009_recipe_alter_inventoryitem_audit_recipeingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='food_image_url',
        ),
        migrations.AddField(
            model_name='recipe',
            name='food_image',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_images/'),
        ),
    ]
