# Generated by Django 5.2.10 on 2026-07-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0010_remove_recipe_food_image_url_recipe_food_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='modifier',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
    ]
