# Generated by Django 5.2.10 on 2026-07-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0011_recipe_modifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=50)),
                ('brand_name', models.CharField(blank=True, default='', max_length=150)),
                ('license_name', models.CharField(blank=True, default='', max_length=150)),
                ('orders', models.IntegerField(default=0)),
                ('net_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cpc', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('advertisement_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
