from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('settings/', views.settings_view, name='settings'),
    path('inventory/', views.inventory_view, name='inventory'),
    path('api/category/add/', views.add_category_api, name='api_add_category'),
    path('api/unit/add/', views.add_unit_api, name='api_add_unit'),
    path('api/vendor/add/', views.add_vendor_api, name='api_add_vendor'),
    path('api/inventory/bulk-add/', views.bulk_add_items_api, name='api_bulk_add'),
    path('api/inventory/ocr-invoice/', views.ocr_invoice_api, name='api_ocr_invoice'),
    path('api/inventory/split-pdf/', views.split_pdf_api, name='api_split_pdf'),
    path('api/inventory/pdf-info/', views.pdf_info_api, name='api_pdf_info'),
    path('api/inventory/lookup-learned/', views.lookup_learned_mapping_api, name='api_lookup_learned'),
    path('api/inventory/delete/', views.delete_inventory_items_api, name='api_delete_inventory_items'),
    path('api/inventory/duplicate/', views.duplicate_inventory_item_api, name='api_duplicate_inventory_item'),
    path('api/inventory/edit/<int:item_id>/', views.edit_inventory_item_api, name='api_edit_inventory_item'),
    path('api/inventory/batch-edit-audit/', views.batch_edit_audit_api, name='api_batch_edit_audit'),
    path('api/manage/<str:item_type>/', views.manage_items_api, name='api_manage_items'),
    path('recipes/', views.recipe_view, name='recipes'),
    path('api/recipes/create/', views.create_recipe_api, name='api_create_recipe'),
    path('api/recipes/edit/<int:recipe_id>/', views.edit_recipe_api, name='api_edit_recipe'),
    path('api/recipes/delete/', views.delete_recipe_api, name='api_delete_recipe'),
    path('api/recipes/duplicate/', views.duplicate_recipe_api, name='api_duplicate_recipe'),
    path('api/recipes/ingredient-lookup/', views.ingredient_lookup_api, name='api_ingredient_lookup'),
    path('sales/commission-invoice/', views.commission_invoice_view, name='commission_invoice'),
    path('api/sales/commission-invoice/scan/', views.scan_commission_invoice_api, name='api_scan_commission'),
    path('api/sales/commission-invoice/add/', views.add_commission_invoice_api, name='api_add_commission'),
    path('api/sales/commission-invoice/edit/<int:item_id>/', views.edit_commission_invoice_api, name='api_edit_commission'),
    path('api/sales/commission-invoice/delete/<int:item_id>/', views.delete_commission_invoice_api, name='api_delete_commission'),
    path('', views.dashboard_view, name='home'),
]
